services:
  database_backend:
    container_name: database_backend
    depends_on:
      - database
    build:
      context: ./
      dockerfile: ./Dockerfile
      # Only will build development stage from our dockerfile
      target: development
    ports:
      - 5000:5000
      - 9229:9229
    networks:
        - tripbot-net
    volumes:
      - ./:/usr/src/app
      - ./src/scripts/init-db.sh:/docker-entrypoint-initdb.d/initialize-database.sh
      - /usr/src/app/node_modules
    command: npm run start
    environment:
      PORT: 5000
      TZ: America/Chicago
      DATABASE_URL: postgres://tripsit:SuperSecure123@database/tripsit

  database_frontend:
    image: dpage/pgadmin4
    container_name: database_frontend
    restart: unless-stopped
    depends_on:
      - database
    volumes:
      - database_admin-data:/var/lib/pgadmin
      - ./src/pgadmin4/servers.json:/pgadmin4/servers.json
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=America/Chicago
      - PGADMIN_DEFAULT_EMAIL=user@tripsit.me
      - PGADMIN_DEFAULT_PASSWORD=SuperSecret123
    ports:
        - 8081:80
    networks:
        - tripbot-net

  database:
    image: postgres:latest
    container_name: database
    ports:
      - 5432:5432  # enables connecting locally via psql
    networks:
        - tripbot-net
    environment:
      POSTGRES_USER: tripsit
      POSTGRES_DB: tripsit
      POSTGRES_PASSWORD: SuperSecure123
      POSTGRES_HOST_AUTH_METHOD: trust

networks:
  tripbot-net:
    name: tripbot-net

volumes:
  tripsit_db-data:
    name: tripsit_db-data
  database_admin-data:
    name: database_admin-data